#!/usr/bin/env python2
from stravasmooth import extractgpx,smoothen,stravaup
import ConfigParser
import argparse

p = argparse.ArgumentParser(description='''Smoothen latest activity on Strava.''')
p.add_argument('-a', '--activity-id' , default=0 , help="Activity id, last activity is taken by default.")
p.add_argument('-g', '--no-graph'    , action='store_false', help="do not create png file showing original and smoothened data.")
p.add_argument('-u', '--no-upload'   , action='store_true' , help="do not upload smoothened data to Strava.")
p.add_argument('-d', '--dry-run'     , action='store_true' , help="do not overwrite original activity when attempting to upload to Strava.")

args = p.parse_args()

filename = extractgpx.extractgpx(args.activity_id)

if not filename == "" :
    smoothen.smoothen(filename,args.no_graph)
    options = "-P  -A run"
    if not args.dry_run :
        options = options + "  -o"
    if not args.no_upload :
        stravaup.main(options+" "+filename+"_smooth.gpx")
